In [123]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [124]:
torch.manual_seed(1)

In [125]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 3]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [126]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [127]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [128]:
print('e^1 equals:', torch.exp(torch.FloatTensor([1])))#exponential function의 구현

e^1 equals: tensor([2.7183])


In [129]:
W = torch.zeros((2, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [130]:
hypothesis = 1/ (1 + torch.exp(-(x_train.matmul(W)+b))) #x*w = torch.matmul(x, w)

In [131]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [132]:
print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))

1/(1+e^{-1}) equals:  tensor([0.7311])


In [133]:
hypothesis = torch.sigmoid(x_train.matmul(W)+b)

In [134]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [135]:
-(y_train[0]*torch.log(hypothesis[0])+ (1-y_train[0])* torch.log(1 - hypothesis[0]))

tensor([0.6931], grad_fn=<NegBackward0>)

In [136]:
losses =  -(y_train*torch.log(hypothesis)+ 
            (1-y_train)* torch.log(1 - hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [137]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [138]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [139]:
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs +1):
    hypothesis = torch.sigmoid(x_train.matmul(W)+b)
    cost= F.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad() # grad를 구한게 있으면 0으로 처리
    cost.backward() #cost에다가 backpropagation 수행
    optimizer.step() #cost 값을 minimize하는 방향으로 업데이트를 한다. 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs,  cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.129368
Epoch  200/1000 Cost: 0.078759
Epoch  300/1000 Cost: 0.057077
Epoch  400/1000 Cost: 0.044895
Epoch  500/1000 Cost: 0.037049
Epoch  600/1000 Cost: 0.031560
Epoch  700/1000 Cost: 0.027498
Epoch  800/1000 Cost: 0.024368
Epoch  900/1000 Cost: 0.021881
Epoch 1000/1000 Cost: 0.019856


In [140]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid= nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [141]:
model = BinaryClassifier()

In [142]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs +1):
    hypothesis = model(x_train)
    cost= F.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad() # grad를 구한게 있으면 0으로 처리
    cost.backward() #cost에다가 backpropagation 수행
    optimizer.step() #cost 값을 minimize하는 방향으로 업데이트를 한다. 
    if epoch % 1 == 0:
        prediction = hypothesis>= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs,  cost.item(), accuracy * 100
        ))

Epoch    0/100 Cost: 0.551150 Accuracy 83.33%
Epoch    1/100 Cost: 0.566579 Accuracy 66.67%
Epoch    2/100 Cost: 0.855197 Accuracy 50.00%
Epoch    3/100 Cost: 2.052620 Accuracy 50.00%
Epoch    4/100 Cost: 0.455371 Accuracy 83.33%
Epoch    5/100 Cost: 0.461365 Accuracy 83.33%
Epoch    6/100 Cost: 0.537601 Accuracy 83.33%
Epoch    7/100 Cost: 0.742166 Accuracy 50.00%
Epoch    8/100 Cost: 1.648683 Accuracy 50.00%
Epoch    9/100 Cost: 0.413893 Accuracy 83.33%
Epoch   10/100 Cost: 0.415840 Accuracy 83.33%
Epoch   11/100 Cost: 0.435836 Accuracy 66.67%
Epoch   12/100 Cost: 0.553400 Accuracy 83.33%
Epoch   13/100 Cost: 0.601067 Accuracy 66.67%
Epoch   14/100 Cost: 1.163023 Accuracy 50.00%
Epoch   15/100 Cost: 0.424122 Accuracy 66.67%
Epoch   16/100 Cost: 0.532746 Accuracy 83.33%
Epoch   17/100 Cost: 0.494740 Accuracy 66.67%
Epoch   18/100 Cost: 0.791055 Accuracy 66.67%
Epoch   19/100 Cost: 0.444038 Accuracy 66.67%
Epoch   20/100 Cost: 0.627249 Accuracy 66.67%
Epoch   21/100 Cost: 0.435866 Accu