In [2]:
import torch
import numpy as np

In [4]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [5]:
#vector +scalar 가능
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[6., 6.]])


In [16]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m2)
print(m1.shape)
print(m2.shape)
print(m1+m2)

tensor([[3.],
        [4.]])
torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


In [19]:
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2))
print(m1*m2)

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [20]:
print(m1.mean())

tensor(2.5000)


In [23]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [25]:
t= torch.FloatTensor([[1,2],[3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [30]:
print(t.sum())

tensor(10.)


In [31]:
print(t.sum(dim=0))

tensor([4., 6.])


In [32]:
print(t.sum(dim=1))

tensor([3., 7.])


In [33]:
print(t.max())

tensor(4.)


In [37]:
print(t.max(dim=0))#두번쨰 값은 큰 값의 인덱스 값이다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [38]:
t= np.array([[[0, 1, 2],
             [3, 4, 5]],
           
            [[6, 7, 8],
             [9, 10, 11]]])
ft= torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [40]:
print(ft.view([-1,3])) #-1값은 유동 적임 즉 총 엘리멘트가 12개이고 두번 째 차원이 3 이므로 -1값은 4가 되어야 한다.
print(ft.view([-1,3]).shape) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [42]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1,1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [44]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [47]:
print(ft.squeeze())#차원이 하나가 줄어들다.
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [48]:
ft= torch.Tensor([0, 1, 2])
print(ft.shape)


torch.Size([3])


In [51]:
print(ft.unsqueeze(0))#dim 0을 늘려랴(3,)-->(1,3)
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [55]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [57]:
print(ft.unsqueeze(1))#(3,)-->(3,1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [59]:
print(ft.unsqueeze(-1)) #마지막 dim 이므로 dim =1 과 같다.
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [60]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [62]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [63]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [64]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [65]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [67]:
print(torch.cat([x, y], dim=0)) # dim 0 이 늘어난다.
print(torch.cat([x, y], dim=1))# dim 1 이 늘어난다.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [68]:
x =torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [70]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [71]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
#unsqueeze(0) dim=0에 대해서 차원을하나 더 만들어라 라는 뜻

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [72]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [74]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [210]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [211]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
